name: Update Google Trends KR

on:
  workflow_dispatch:
  schedule:
    # 매일 08:05 KST (KST-9h = 23:05 UTC)
    - cron: "5 23 * * *"

permissions:
  contents: write

jobs:
  update-trends:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Update trends JSON
        env:
          # 있으면 자동 폴백 사용 (선택)
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
        run: node scripts/update_trends_kr.cjs

      - name: Commit & push if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add data/trends-kr.json
            git commit -m "auto: update trends KR"
            git push
          else
            echo "No changes."
          fi
