# .github/workflows/update-trends.yml
name: Update Google Trends KR

on:
  workflow_dispatch:      # 수동 실행
  schedule:
    - cron: "15 0 * * *"  # 매일 00:15 UTC (KST 오전 9:15) 자동 실행

permissions:
  contents: write

jobs:
  update-trends:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run updater
        run: node scripts/update_trends_kr.cjs

      - name: Commit & push JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/trends-kr.json
          git commit -m "auto: update trends KR" || echo "no changes"
          git push
